version: 2

packer: &packer
  docker:
    - image: hashicorp/packer:light

jobs:
  build:
    <<: *packer
    steps:
      - checkout
      - run:
          name: validate
          command: packer validate packer.json
      - run:
          name: build
          command: packer build packer.json
